config/routes.rb
Rails.application.routes.draw do
  get 'arrival/list' => 'arrivals#list'
  post 'arrival/list' => 'arrivals#list'
  get 'arrival/unitlist' => 'arrivals#unitlist'
  post 'arrival/unitlist' => 'arrivals#unitlist'
  get 'arrival/query' => 'arrivals#query'
  post 'arrival/query' => 'arrivals#query'
  get 'arrival/result' => 'arrivals#result'
  post 'arrival/result' => 'arrivals#result'

  get 'pt_barcode/search' => 'pt_barcodes#search'
  post 'pt_barcode/search' => 'pt_barcodes#search'

  get 'us_barcode/search' => 'us_barcodes#search'
  post 'us_barcode/search' => 'us_barcodes#search'
  get 'us_barcodes/site_current_uid/:id' => 'us_barcodes#site_current_uid', as: 'us_barcodes/site_current_uid'

  resources :holidays
  resources :works

  resources :schedules
  get 'schedule/editpage/:id' => 'schedules#editpage', as: 'schedules/editpage'  #need sort get id before no get id url, system will use get id route first. @xieyinghua
  get 'schedule/editpage' => 'schedules#editpage'
  post 'schedule/editpage' => 'schedules#editpage'
  get 'schedule/updatepage' => 'schedules#updatepage'
  post 'schedule/updatepage' => 'schedules#updatepage'

  get 'schedule/editrole/:id' => 'schedules#editrole', as: 'schedules/editrole'  #need sort get id before no get id url, system will use get id route first. @xieyinghua
  get 'schedule/editrole' => 'schedules#editrole'
  post 'schedule/editrole' => 'schedules#editrole'
  get 'schedule/updaterole' => 'schedules#updaterole'
  post 'schedule/updaterole' => 'schedules#updaterole'

  get 'wk_barcode/search' => 'wk_barcodes#search'
  post 'wk_barcode/search' => 'wk_barcodes#search'

  get 'rf_barcode/search' => 'rf_barcodes#search'
  post 'rf_barcode/search' => 'rf_barcodes#search'

  root to:'root#home'
  get 'test' => 'root#test'

  

  resources :users
  resources :sites
  resource :session, only: [ :new, :create, :destroy ]

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:restdate, :resttype)
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 班表排班系統 > 國定假日設定</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>國定假日設定</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;padding-left:5%;'>
      

<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restdate %><br>
    <%= f.date_select :restdate %>
  </div>
  <div class="field">
    <%= f.label :resttype %><br>
    <%= f.text_field :resttype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




      <%= link_to '返回', holidays_path %>
      
    </div>
  </div>
</div>

app/views/holidays/edit.html.erb
<%= render 'form' %>

app/views/holidays/index.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 管理系統 > 國定假日設定</p>

<div style='background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>國定假日設定</div>

<table class="table">
  <thead>
    <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
      <th><%= t(:restdate, :scope=>[:activerecord,:attributes,:holiday]) %></th>
      <th><%= t(:resttype, :scope=>[:activerecord,:attributes,:holiday]) %></th>
      <% if(current_user.uid=='9999' || current_user.upower=='管理員') %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
        <td><%= holiday.restdate %></td>
        <td><%= holiday.resttype %></td>
        <% if(current_user.uid=='9999' || current_user.upower=='管理員') %>
          <td><%= link_to '詳細', holiday %></td>
          <td><%= link_to '修改', edit_holiday_path(holiday) %></td>
          <td><%= link_to '刪除', holiday, method: :delete, data: { confirm: '確定嗎？' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if(current_user.uid=='9999' || current_user.upower=='管理員') %>
  <%= link_to '新增國定假日', new_holiday_path, :class=>"btn btn-large btn-primary" %>
<% end %>
<br>
<br>

app/views/holidays/new.html.erb
<%= render 'form' %>

app/views/holidays/show.html.erb
<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 班表排班系統 > 國定假日設定</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>國定假日設定</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;padding-left:5%;'>



<p id="notice"><%= notice %></p>

<p>
  <strong><%= t(:restdate, :scope=>[:activerecord,:attributes,:holiday]) %>:</strong>
  <%= @holiday.restdate %>
</p>

<p>
  <strong><%= t(:resttype, :scope=>[:activerecord,:attributes,:holiday]) %>:</strong>
  <%= @holiday.resttype %>
</p>

<%= link_to '修改', edit_holiday_path(@holiday) %> |
<%= link_to '返回', holidays_path %>




    </div>
  </div>
</div>