config/routes.rb
Rails.application.routes.draw do
  get 'arrival/list' => 'arrivals#list'
  post 'arrival/list' => 'arrivals#list'
  get 'arrival/unitlist' => 'arrivals#unitlist'
  post 'arrival/unitlist' => 'arrivals#unitlist'
  get 'arrival/query' => 'arrivals#query'
  post 'arrival/query' => 'arrivals#query'
  get 'arrival/result' => 'arrivals#result'
  post 'arrival/result' => 'arrivals#result'

  get 'pt_barcode/search' => 'pt_barcodes#search'
  post 'pt_barcode/search' => 'pt_barcodes#search'

  get 'us_barcode/search' => 'us_barcodes#search'
  post 'us_barcode/search' => 'us_barcodes#search'
  get 'us_barcodes/site_current_uid/:id' => 'us_barcodes#site_current_uid', as: 'us_barcodes/site_current_uid'

  resources :holidays
  resources :works

  resources :schedules
  get 'schedule/editpage/:id' => 'schedules#editpage', as: 'schedules/editpage'  #need sort get id before no get id url, system will use get id route first. @xieyinghua
  get 'schedule/editpage' => 'schedules#editpage'
  post 'schedule/editpage' => 'schedules#editpage'
  get 'schedule/updatepage' => 'schedules#updatepage'
  post 'schedule/updatepage' => 'schedules#updatepage'

  get 'schedule/editrole/:id' => 'schedules#editrole', as: 'schedules/editrole'  #need sort get id before no get id url, system will use get id route first. @xieyinghua
  get 'schedule/editrole' => 'schedules#editrole'
  post 'schedule/editrole' => 'schedules#editrole'
  get 'schedule/updaterole' => 'schedules#updaterole'
  post 'schedule/updaterole' => 'schedules#updaterole'

  get 'wk_barcode/search' => 'wk_barcodes#search'
  post 'wk_barcode/search' => 'wk_barcodes#search'

  get 'rf_barcode/search' => 'rf_barcodes#search'
  post 'rf_barcode/search' => 'rf_barcodes#search'

  root to:'root#home'
  get 'test' => 'root#test'

  

  resources :users
  resources :sites
  resource :session, only: [ :new, :create, :destroy ]

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
    site=Site.all.where("sanem not like '洗滌機%'")
  end

  # GET /schedules/1/edit
  def editpage
    #確定一下要抓的日期是這個月，還是其它有被指定的月份
    @target_date=params[:target_date]
    if @target_date!=nil
      @target_date = DateTime.parse(@target_date)

      if params[:commit]=='下一天'
        @target_date+=1.day
      elsif params[:commit]=='前一天'
        @target_date-=1.day
      end
    else
      @target_date=Date.today
    end
    @d_now=@target_date.strftime("%Y/%m/%d")


    #初始化用得到的資料
    @works=Work.all.order("wsort asc")
    @results=Hash.new

    #整合班表，找出最近一天的班表
    @schedules_where=Schedule.all.where("workdate<='#{@d_now}'")
    @schedules_where=@schedules_where.order('workdate desc')
    @schedules_where=@schedules_where.limit(1)
    workdate=@schedules_where[0][:workdate]


    @schedules_result=Schedule.all.where("workdate='#{workdate}'")
    @schedules_result.each(){|schedule|
    
=begin  
      #原本的，有做格式的轉置
      if schedule.site=='洗滌台'
        wname='洗淨室'
      elsif schedule.site=='洗滌機'
        wname='消毒室'
      else
        wname=schedule.site
      end


      flag=false
      w=@works.where("wname='#{wname}'")
      if(w==[])
        w=@works.where("wname='#{wname}一'")
        if(w!=[])
          flag=true
          #p 'flag true'
        end
      end

      if schedule.workpart=='上午'
        #p flag
        if(flag)
          if(@results[:"p1_#{wname}一"]==nil)
            @results[:"p1_#{wname}一"]=schedule.uid
            #p wname+'一'
          elsif(@results[:"p1_#{wname}二"]==nil)
            @results[:"p1_#{wname}二"]=schedule.uid
            #p wname+'二'
          else
            @results[:"p1_#{wname}三"]=schedule.uid
            #p wname+'三'
          end
        else
          @results[:"p1_#{wname}"]=schedule.uid
          #p wname
        end
      elsif schedule.workpart=='下午'
        if(flag)
          if(@results[:"p2_#{wname}一"]==nil)
            @results[:"p2_#{wname}一"]=schedule.uid
          elsif(@results[:"p2_#{wname}二"]==nil)
            @results[:"p2_#{wname}二"]=schedule.uid
          else
            @results[:"p2_#{wname}三"]=schedule.uid
          end
        else
          @results[:"p2_#{wname}"]=schedule.uid
        end
      end
=end
      #新的，不做格式的轉置
      wname=schedule.site.gsub(/洗滌機/,'消毒室').gsub(/洗滌台/,'洗淨室')
      if schedule.workpart=='上午'
        @results[:"p1_#{wname}"]=schedule.uid
      elsif schedule.workpart=='下午'
        @results[:"p2_#{wname}"]=schedule.uid
      end
    }
  end


  #write excel. @xieyinghua
  def editrole_writeexcel() 
    # Create a new Excel Worksense
    if Rails.env.production?
      #@wlink='../List.xls'  #tomcat version,
      @wlink='public/List.xls'
      @rlink='../List.xls'
    else
      @wlink='public/List.xls'
      @rlink='../List.xls'
    end
    worksense = WriteExcel.new(@wlink)


    # Add worksheet(s)
    worksheet  = worksense.add_worksheet

    # Add and define a format
    format = worksense.add_format
    format.set_bold
    format.set_align('center')
    format.set_text_warp(true)


    # write title
    worksheet.set_column(0, 0, 20)
    worksheet.write(0, 0, '人員', format)
    @dayscount.times(){|day|
      worksheet.write(0, day+1, "#{day+1}號", format)
    }
    worksheet.write(0, @dayscount+1, '總計', format)
    worksheet.set_column('AG:AG', 70)
    

    #write body
    row=0
    @users.each(){|user|
      row+=1


      worksheet.write(row, 0, user.uname, format)

      @dayscount.times(){|day|
        worksheet.write(row, day+1, @results[:"p1_#{user.uid}_#{day}"])
      }

      
      data=''
      @works.each(){|work|
        if @results[:"#{user.uid}_#{work.wname}"]==nil
          data+=(work.wsort.to_s()+':0 ')
        else
          data+=(work.wsort.to_s()+':'+@results[:"#{user.uid}_#{work.wname}"].to_s()+' ')
        end
      }
      worksheet.write(row, @dayscount+1, data)

      
      row+=1


      @dayscount.times(){|day|
        worksheet.write(row, day+1, @results[:"p2_#{user.uid}_#{day}"])
      }

    }


    #write foot
    row+=1
    worksheet.set_row(35, 180, nil, 0, 1)
    worksheet.write(row, 0, '當日總計', format)
    @dayscount.times(){|day|
      data="上午:\n"
      @works.each(){|work|
        if @results[:"p1_#{day}_#{work.wname}"]==nil
          data+=(work.wsort.to_s()+":0\n")
        else
          data+=(work.wsort.to_s()+':'+@results[:"p1_#{day}_#{work.wname}"].to_s()+"\n")
        end
      }
      data+="下午:\n"
      @works.each(){|work|
        if @results[:"p2_#{day}_#{work.wname}"]==nil
          data+=(work.wsort.to_s()+":0\n")
        else
          data+=(work.wsort.to_s()+':'+@results[:"p2_#{day}_#{work.wname}"].to_s()+"\n")
        end
      }
      worksheet.write(row, day+1, data)
    }


    # write to file
    worksense.close
  end

  # GET /schedules/1/edit
  def editrole
    #初始化相關參數
    @results=Hash.new
    @users=User.all.where("utitle='護理師' and upower!='停用'").order('usort asc')
    @works=Work.all.order("wsort asc")
    @holiday = Holiday.all

    #確定一下要抓的日期是這個月，還是其它有被指定的月份
    @target_date=params[:target_date]
    if @target_date!=nil
      @target_date = DateTime.parse(@target_date)

      if params[:commit]=='下個月'
        @target_date+=1.months
      elsif params[:commit]=='上個月'
        @target_date-=1.months
      end
    else
      @target_date=Date.today
    end
    @d_now=@target_date.strftime("%Y/%m/%d")
    @ym_now=@target_date.strftime("%Y/%m")
    @m_now=@target_date.strftime("%m")
    @dayscount=days_in_month(@m_now.to_i())

    


    #列舉月份的資料
    @schedules=Schedule.all.where("workdate>='#{@ym_now}/01' and workdate<='#{@ym_now}/#{@dayscount}'")
    @schedules.each(){|schedule|
      day=schedule.workdate.strftime("%d").to_i()-1


      #用來給前端顯示每一個人每一天每一節班表的資料
      if schedule.workpart=='上午'

        if schedule.wid!=nil
          work=Work.find_by(:wid=>schedule.wid)
          if work!=nil
            @results[:"p1_#{schedule.uid}_#{day}"]=work.wname
            site_name=@results[:"p1_#{schedule.uid}_#{day}"]  #記錄下來翻譯好的名稱，以給後續的人員統計及日期統計使用
          end
        end


        #用來給前端顯示每一天上午的班表統計
        if @results[:"p1_#{day}_#{site_name}"]==nil
          @results[:"p1_#{day}_#{site_name}"]=1
        else
          @results[:"p1_#{day}_#{site_name}"]+=1
        end

      else

        if schedule.site!=nil
          work=Work.find_by(:wid=>schedule.wid)
          if work!=nil
            @results[:"p2_#{schedule.uid}_#{day}"]=work.wname
            site_name=@results[:"p2_#{schedule.uid}_#{day}"]  #記錄下來翻譯好的名稱，以給後續的人員統計及日期統計使用
          end
        end


        #用來給前端顯示每一天下午的班表統計
        if @results[:"p2_#{day}_#{site_name}"]==nil
          @results[:"p2_#{day}_#{site_name}"]=1
        else
          @results[:"p2_#{day}_#{site_name}"]+=1
        end

      end



      #用來給前端顯示每一個人的班表統計
      if @results[:"#{schedule.uid}_#{site_name}"]==nil
        @results[:"#{schedule.uid}_#{site_name}"]=1
      else
        @results[:"#{schedule.uid}_#{site_name}"]+=1
      end

      #用來給前端顯示每一天的班表統計
      #if @results[:"#{day}_#{site_name}"]==nil
      #  @results[:"#{day}_#{site_name}"]=1
      #else
      #  @results[:"#{day}_#{site_name}"]+=1
      #end
    }




    editrole_writeexcel()
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def updatepage
    #組合params
    @d_now=Date.today.strftime("%Y/%m/%d")
    


    #寫入的資料只處理護理師的
    @users=User.all.where("utitle='護理師'")
    #找出所有的工作
    @works=Work.all.order("wsort asc")



    #寫入這天的上午班表
    @works.each(){|work|
      uid=params[:"p1_#{work.wname}"]
      if @user==nil
        uname=''
      else
        uname=@user[:uname]
      end
=begin
      #原本的，有做格式的轉置
      if(work.wname=='洗淨室一' || work.wname=='洗淨室二')
        wname='洗滌台'
      elsif(work.wname=='消毒室')
        wname='洗滌機'
      else
        wname=work.wname.gsub('一','').gsub('二','').gsub('三','')
      end
=end
      #新的，不做格式的轉置
      if(work.wname=='洗淨室一')
        wname='洗滌台一'
      elsif(work.wname=='洗淨室二')
        wname='洗滌台二'
      elsif(work.wname=='洗淨室三')
        wname='洗滌台三'
      elsif(work.wname=='消毒室')
        wname='洗滌機'
      else
        wname=work.wname
      end
      @result=Schedule.find_by(:workdate=>@d_now, :workpart=>'上午', :site=>wname)
      if @result==nil
        @schedule = Schedule.new(:workdate=>@d_now, :workpart=>'上午', :site=>wname, :uid=>uid, :uname=>uname)
        @schedule.save
      else
        @result.update(:workdate=>@d_now, :workpart=>'上午', :site=>wname, :uid=>uid, :uname=>uname)
      end
    }


    #寫入這天的下午時段
    @works.each(){|work|
      uid=params[:"p2_#{work.wname}"]
      if @user==nil
        uname=''
      else
        uname=@user[:uname]
      end
=begin
      #原本的，有做格式的轉置

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 班表排班系統 > 班表管理</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>班表管理</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;padding-left:5%;'>


<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workdate %><br>
    <%= f.date_select :workdate %>
  </div>
  <div class="field">
    <%= f.label :workpart %><br>
    <%= f.text_field :workpart %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :uname %><br>
    <%= f.text_field :uname %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




      <%= link_to '返回', schedules_path %>

    </div>
  </div>
</div>

app/views/schedules/_formpage.html.erb
<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 班表排班系統 > 今日-場地排班</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>今日-場地排班</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;'>
      

      <%= form_tag :action => 'editpage' do %>
        <br><br>
        <p style='display:inline-block;color:#333333;font-size:16px;font-family:PingFang-SC-Medium;margin-left:5%;width:300px;'>
          <%= hidden_field_tag(:target_date, @target_date) %>
          <%= submit_tag :prev, :value=>'前一天', :class=>"btn btn-large btn-primary" %>
          <%= submit_tag :next, :value=>'下一天', :class=>"btn btn-large btn-primary" %>
        </p>
      <% end %>

      <%= form_tag :action => 'updatepage' do %>
        <br><br>
        <!-- map all scopy data to array variant, and show it to options_for_select. @xieyinghua -->
        <% user_array = User.all.map{|user| [user.uname,user.uid] if user.utitle=='護理師' && user.upower!='停用'}.uniq %>


        <p style='display:inline-block;color:#333333;font-size:16px;font-family:PingFang-SC-Medium;margin-left:5%;width:300px;'>
          <%= t(:workdate, :scope=>[:activerecord,:attributes,:schedule]) %>：<%= text_field_tag :p1workdate_text, @d_now, :disabled=>true %>
        </p>
        <p style='display:inline-block;color:#333333;font-size:16px;font-family:PingFang-SC-Medium;margin-left:5%;width:300px;'>
          <%= t(:workpart, :scope=>[:activerecord,:attributes,:schedule]) %>：<%= text_field_tag :p1workpart_text, '上午', :disabled=>true %>
        </p>
        <br>


        <% @works.each_with_index(){|work,i| %>
          <p style='display:inline-block;color:#333333;font-size:16px;font-family:PingFang-SC-Medium;margin-left:5%;width:120px;'>
          <%= "#{work.wsort}.#{work.wname}" %>：<%= select_tag :"p1_#{work.wname}", options_for_select(user_array, @results[:"p1_#{work.wname}"]) %>
          </p>
          <% if (i+1)%5==0 %>
            <br><br>
          <% end %>
        <% } %>
        <br>
        <br>
        <br>
        <br>

        <p style='display:inline-block;color:#333333;font-size:16px;font-family:PingFang-SC-Medium;margin-left:5%;width:300px;'>
          <%= t(:workdate, :scope=>[:activerecord,:attributes,:schedule]) %>：<%= text_field_tag :p2workdate_text, @d_now, :disabled=>true %>
        </p>
        <p style='display:inline-block;color:#333333;font-size:16px;font-family:PingFang-SC-Medium;margin-left:5%;width:300px;'>
          <%= t(:workpart, :scope=>[:activerecord,:attributes,:schedule]) %>：<%= text_field_tag :p2workpart_text, '下午', :disabled=>true %>
        </p>
        <br>

        <% @works.each_with_index(){|work,i| %>
          <p style='display:inline-block;color:#333333;font-size:16px;font-family:PingFang-SC-Medium;margin-left:5%;width:120px;'>
          <%= "#{work.wsort}.#{work.wname}" %>：<%= select_tag :"p2_#{work.wname}", options_for_select(user_array, @results[:"p2_#{work.wname}"]) %>
          </p>
          <% if (i+1)%5==0 %>
            <br><br>
          <% end %>
        <% } %>
        <br>
        <br>
        <br>
        <br>

        <br>
        <br>

        <% if(current_user.uid=='9999' || current_user.upower=='管理員') %>
          <center><%= submit_tag '更新', :class=>"btn btn-large btn-primary" %></center>
        <% end %>
        
        <br>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/_formrole1.html.erb
<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 班表排班系統 > 本月-班表草稿</p>

<div style='display:table;width:2560px;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>本月-班表草稿</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;'>
      

      <%= form_tag :action => 'updaterole' do %>
        <br><br>
        <!-- map all scopy data to array variant, and show it to options_for_select. @xieyinghua -->
        <% work_array = Work.all.map{|work| [work.wname] }.uniq %>


        <p style='font-size:48px;font-family:PingFang-SC-Medium;'><%= @ym_now %>上午班表</p>
        <table>

          <tr style="width:2560px; height:38px; background:#222222">
            <td style='border:3px #cccccc solid;color:white;'>
                日 期 ：
            </td>
            <% @dayscount.times(){|day| %>
              <td style='border:3px #cccccc solid;color:white;'>
                <center><%= day+1 %>號</center>
              </td>
            <% } %>
          </tr>

          
          <% @users.each(){|user| %>
            <tr style="width:2560px; height:50px; background:#ceebe9">
              <td style='border:3px #cccccc solid;'>
                <%= user.uname %>：
              </td>
              <% @dayscount.times(){|day| %>
                <td style='border:3px #cccccc solid;'>
                  <%= select_tag :"p1_#{user.uid}_#{day}", options_for_select(work_array, @results[:"p1_#{user.uid}_#{day}"]) %>
                </td>
              <% } %>
            </tr>
          <% } %>
        </table>

        <br>
        <br>

        <p style='font-size:48px;font-family:PingFang-SC-Medium;'><%= @ym_now %>下午班表</p>
        <table>

          <tr style="width:2560px; height:38px; background:#222222">
            <td style='border:3px #cccccc solid;color:white;'>
                日 期 ：
            </td>
            <% @dayscount.times(){|day| %>
              <td style='border:3px #cccccc solid;color:white;'>
                <center><%= day+1 %>號</center>
              </td>
            <% } %>
          </tr>

          
          <% @users.each(){|user| %>
            <tr style="width:2560px; height:50px; background:#f3e4dd">
              <td style='border:3px #cccccc solid;'>
                <%= user.uname %>：
              </td>
              <% @dayscount.times(){|day| %>
                <td style='border:3px #cccccc solid;'>
                  <%= select_tag :"p2_#{user.uid}_#{day}", options_for_select(work_array, @results[:"p2_#{user.uid}_#{day}"]) %>
                </td>
              <% } %>
            </tr>
          <% } %>
        
        </table>

        <br>
        <br>

        <center><%= submit_tag '更新', :class=>"btn btn-large btn-primary" %></center>

        <br>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/edit.html.erb
<%= render 'form' %>

app/views/schedules/editpage.html.erb
<%= render 'formpage' %>

app/views/schedules/editrole.html.erb
<%= render 'formrole' %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 班表排班系統 > 班表管理</p>

<div style='background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>班表管理</div>

<table class="table">
  <thead>
    <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
      <th><%= t(:workdate, :scope=>[:activerecord,:attributes,:schedule]) %></th>
      <th><%= t(:workpart, :scope=>[:activerecord,:attributes,:schedule]) %></th>
      <th><%= t(:uid, :scope=>[:activerecord,:attributes,:schedule]) %></th>
      <th><%= t(:uname, :scope=>[:activerecord,:attributes,:schedule]) %></th>
      <th><%= t(:site, :scope=>[:activerecord,:attributes,:schedule]) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
        <td><%= schedule.workdate %></td>
        <td><%= schedule.workpart %></td>
        <td><%= schedule.uid %></td>
        <td><%= schedule.uname %></td>
        <td><%= schedule.site %></td>
        <td><%= link_to '詳細', schedule %></td>
        <td><%= link_to '修改', edit_schedule_path(schedule) %></td>
        <td><%= link_to '刪除', schedule, method: :delete, data: { confirm: '確定嗎？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增班表', new_schedule_path, :class=>"btn btn-large btn-primary"  %>

<br>
<br>

app/views/schedules/new.html.erb
<%= render 'form' %>

app/views/schedules/show.html.erb
<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 班表排班系統 > 班表管理</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>班表管理</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;padding-left:5%;'>



<p id="notice"><%= notice %></p>

<p>
  <strong><%= t(:workdate, :scope=>[:activerecord,:attributes,:schedule]) %>:</strong>
  <%= @schedule.workdate %>
</p>

<p>
  <strong><%= t(:workpart, :scope=>[:activerecord,:attributes,:schedule]) %>:</strong>
  <%= @schedule.workpart %>
</p>

<p>
  <strong><%= t(:uid, :scope=>[:activerecord,:attributes,:schedule]) %>:</strong>
  <%= @schedule.uid %>
</p>

<p>
  <strong><%= t(:uname, :scope=>[:activerecord,:attributes,:schedule]) %>:</strong>
  <%= @schedule.uname %>
</p>

<p>
  <strong><%= t(:site, :scope=>[:activerecord,:attributes,:schedule]) %>:</strong>
  <%= @schedule.site %>
</p>

<%= link_to '修改', edit_schedule_path(@schedule) %> |
<%= link_to '返回', schedules_path %>





    </div>
  </div>
</div>