config/routes.rb
Rails.application.routes.draw do
  get 'arrival/list' => 'arrivals#list'
  post 'arrival/list' => 'arrivals#list'
  get 'arrival/unitlist' => 'arrivals#unitlist'
  post 'arrival/unitlist' => 'arrivals#unitlist'
  get 'arrival/query' => 'arrivals#query'
  post 'arrival/query' => 'arrivals#query'
  get 'arrival/result' => 'arrivals#result'
  post 'arrival/result' => 'arrivals#result'

  get 'pt_barcode/search' => 'pt_barcodes#search'
  post 'pt_barcode/search' => 'pt_barcodes#search'

  get 'us_barcode/search' => 'us_barcodes#search'
  post 'us_barcode/search' => 'us_barcodes#search'
  get 'us_barcodes/site_current_uid/:id' => 'us_barcodes#site_current_uid', as: 'us_barcodes/site_current_uid'

  resources :holidays
  resources :works

  resources :schedules
  get 'schedule/editpage/:id' => 'schedules#editpage', as: 'schedules/editpage'  #need sort get id before no get id url, system will use get id route first. @xieyinghua
  get 'schedule/editpage' => 'schedules#editpage'
  post 'schedule/editpage' => 'schedules#editpage'
  get 'schedule/updatepage' => 'schedules#updatepage'
  post 'schedule/updatepage' => 'schedules#updatepage'

  get 'schedule/editrole/:id' => 'schedules#editrole', as: 'schedules/editrole'  #need sort get id before no get id url, system will use get id route first. @xieyinghua
  get 'schedule/editrole' => 'schedules#editrole'
  post 'schedule/editrole' => 'schedules#editrole'
  get 'schedule/updaterole' => 'schedules#updaterole'
  post 'schedule/updaterole' => 'schedules#updaterole'

  get 'wk_barcode/search' => 'wk_barcodes#search'
  post 'wk_barcode/search' => 'wk_barcodes#search'

  get 'rf_barcode/search' => 'rf_barcodes#search'
  post 'rf_barcode/search' => 'rf_barcodes#search'

  root to:'root#home'
  get 'test' => 'root#test'

  

  resources :users
  resources :sites
  resource :session, only: [ :new, :create, :destroy ]

end

app/models/site.rb
class Site < ActiveRecord::Base
	#custom add relationship. @xieyinghua
	has_many :worksenses, :foreign_key => :site_id
	has_many :barcodes, :foreign_key => :site_id
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all.order('id asc')
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:sname)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 管理系統 > 內視鏡場域清單</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>內視鏡場域清單</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;padding-left:5%;'>
      



<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sname %><br>
    <%= f.text_field :sname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




      <%= link_to '返回', sites_path %>

    </div>
  </div>
</div>

app/views/sites/edit.html.erb
<%= render 'form' %>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 管理系統 > 內視鏡場域清單</p>

<div style='background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>內視鏡場域清單</div>

<table class="table">
  <thead>
    <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
      <th><%= t(:sname, :scope=>[:activerecord,:attributes,:site]) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
        <td><%= site.sname %></td>
        <td><%= link_to '詳細', site %></td>
        <td><%= link_to '修改', edit_site_path(site) %></td>
        <td><%= link_to '刪除', site, method: :delete, data: { confirm: '確定嗎？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增場地', new_site_path, :class=>"btn btn-large btn-primary" %>

<br>
<br>

app/views/sites/new.html.erb
<%= render 'form' %>

app/views/sites/show.html.erb
<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 管理系統 > 內視鏡場域清單</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1280px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>內視鏡場域清單</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;padding-left:5%;'>
      



<p id="notice"><%= notice %></p>

<p>
  <strong><%= t(:sname, :scope=>[:activerecord,:attributes,:site]) %>:</strong>
  <%= @site.sname %>
</p>

<%= link_to '修改', edit_site_path(@site) %> |
<%= link_to '返回', sites_path %>





    </div>
  </div>
</div>